CREATE TABLE PRODUCTS
(
    PRODUCT_ID            int NOT NULL,
    PRODUCT_NAME          VARCHAR(128) ,
    PRODUCT_CATEGORY      VARCHAR(128) ,
    PRODUCT_DESC          VARCHAR(1024) ,
    PRODUCT_PRICE         NUMERIC(10,2) ,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE USERS
(
    USERNAME              VARCHAR(32) NOT NULL ,
    PASSWORD              VARCHAR(32) NOT NULL ,
CONSTRAINT USERNAME_PK PRIMARY KEY (USERNAME)
);

CREATE SEQUENCE product_id_sq;
ALTER TABLE PRODUCTS
ALTER COLUMN PRODUCT_ID
SET DEFAULT NEXTVAL('product_id_sq');